// Source lists for the reference-search vocabulary. build-vocab.mjs expands these into phrases,
// embeds each phrase with MobileCLIP-S0's text encoder, and writes public/refs/.
// Keep entries lowercase; commas separate synonyms that share one meaning ("longsword, sword").

export const SUBJECTS = [
  'man',
  'woman',
  'boy',
  'girl',
  'old man',
  'old woman',
  'child',
  'figure',
  'person',
  'couple',
  'knight',
  'warrior',
  'soldier',
  'samurai',
  'ninja',
  'viking',
  'gladiator',
  'paladin',
  'barbarian',
  'monk',
  'rogue',
  'thief',
  'assassin',
  'archer',
  'ranger',
  'hunter',
  'wizard',
  'witch',
  'sorcerer',
  'mage',
  'necromancer',
  'cleric',
  'priest',
  'druid',
  'bard',
  'pirate',
  'sailor',
  'king',
  'queen',
  'prince',
  'princess',
  'noble',
  'merchant',
  'blacksmith',
  'farmer',
  'peasant',
  'elf',
  'dwarf',
  'orc',
  'goblin',
  'halfling',
  'tiefling',
  'dragonborn',
  'giant',
  'angel',
  'demon',
  'vampire',
  'zombie',
  'skeleton',
  'ghost',
  'cyborg',
  'robot',
  'astronaut',
  'mercenary',
  'bounty hunter',
  'swordsman',
  'swordswoman',
  'spearman',
  'dancer',
  'martial artist',
];

export const ACTIONS = [
  'holding a sword',
  'holding a sword overhead',
  'holding a sword two-handed',
  'swinging a sword',
  'drawing a sword',
  'sheathing a sword',
  'sword over the shoulder',
  'holding a sword and shield',
  'blocking with a shield',
  'holding a spear',
  'thrusting a spear',
  'throwing a spear',
  'drawing a bow',
  'aiming a bow',
  'holding an axe',
  'swinging an axe',
  'holding a hammer',
  'holding a staff',
  'holding a dagger',
  'dual wielding',
  'holding a gun',
  'aiming a gun',
  'holding a bow',
  'holding a crossbow',
  'holding a shield',
  'holding a scythe',
  'holding a katana',
  'holding a whip',
  'holding a wand',
  'holding a book',
  'holding a skull',
  'holding a flower',
  'holding a banner',
  'holding a baby',
  'casting a spell',
  'holding a torch',
  'holding a lantern',
  'reading a book',
  'holding a cup',
  'carrying a sack',
  'running',
  'sprinting',
  'walking',
  'jumping',
  'leaping',
  'falling',
  'flying',
  'floating',
  'climbing',
  'crouching',
  'kneeling',
  'sitting',
  'sitting on a throne',
  'lying down',
  'sleeping',
  'dying',
  'wounded',
  'fighting',
  'dueling',
  'punching',
  'kicking',
  'high kick',
  'lunging',
  'charging',
  'dodging',
  'rolling',
  'blocking',
  'parrying',
  'attacking',
  'riding a horse',
  'riding a dragon',
  'dancing',
  'praying',
  'meditating',
  'bowing',
  'saluting',
  'pointing',
  'reaching out',
  'arms crossed',
  'hands on hips',
  'arms raised',
  'arms spread',
  'looking up',
  'looking back',
  'looking over shoulder',
  'leaning on a wall',
  'stretching',
  'screaming',
  'laughing',
  'crying',
  'hugging',
  'carrying someone',
  'pulling a rope',
  'pushing',
  'throwing',
  'catching',
  'standing',
  'standing heroically',
  'walking away',
  'turning around',
];

// Short action words that also stand alone in queries.
export const POSE_WORDS = [
  'dynamic pose',
  'action pose',
  'fighting stance',
  'battle stance',
  'heroic pose',
  'contrapposto',
  'gesture',
  'foreshortening',
  'mid-swing',
  'mid-air',
  'midair',
  'in motion',
  'motion blur',
  'overhead strike',
  'downward slash',
  'upward slash',
  'sword slash',
  'sword thrust',
  'sword lunge',
  'spin attack',
  'jump attack',
  'flying kick',
  'guard stance',
  'low stance',
  'two-handed',
  'one-handed',
  'off balance',
  'twisting',
  'recoil',
  'impact',
  'battle cry',
  'victory pose',
  'defeated',
  'kneeling knight',
  'stickman',
  'stick figure',
  'figure drawing',
  'gesture drawing',
  'pose reference',
  'anatomy reference',
  'hand pose',
  'hands',
  'feet',
  'face',
  'portrait',
  'full body',
  'half body',
  'upper body',
  'close-up',
  'silhouette',
];

export const CREATURES = [
  'dragon',
  'wyvern',
  'drake',
  'hydra',
  'serpent',
  'sea serpent',
  'basilisk',
  'griffin',
  'gryphon',
  'phoenix',
  'pegasus',
  'unicorn',
  'manticore',
  'chimera',
  'minotaur',
  'centaur',
  'harpy',
  'siren',
  'mermaid',
  'kraken',
  'leviathan',
  'beholder',
  'mind flayer',
  'owlbear',
  'displacer beast',
  'troll',
  'ogre',
  'cyclops',
  'golem',
  'elemental',
  'fire elemental',
  'treant',
  'ent',
  'dryad',
  'fairy',
  'pixie',
  'imp',
  'gargoyle',
  'wraith',
  'lich',
  'banshee',
  'werewolf',
  'yeti',
  'kitsune',
  'oni',
  'tengu',
  'naga',
  'lamia',
  'slime',
  'ooze',
  'mimic',
  'giant spider',
  'giant worm',
  'sandworm',
  'wolf',
  'dire wolf',
  'fox',
  'bear',
  'lion',
  'tiger',
  'panther',
  'leopard',
  'cheetah',
  'lynx',
  'deer',
  'stag',
  'elk',
  'moose',
  'horse',
  'stallion',
  'warhorse',
  'mule',
  'boar',
  'bull',
  'bison',
  'ram',
  'goat',
  'elephant',
  'rhino',
  'hippo',
  'giraffe',
  'camel',
  'gorilla',
  'monkey',
  'bat',
  'rat',
  'mouse',
  'rabbit',
  'hare',
  'squirrel',
  'badger',
  'raccoon',
  'otter',
  'owl',
  'eagle',
  'hawk',
  'falcon',
  'raven',
  'crow',
  'vulture',
  'parrot',
  'peacock',
  'swan',
  'heron',
  'crane',
  'penguin',
  'snake',
  'cobra',
  'python',
  'lizard',
  'chameleon',
  'crocodile',
  'alligator',
  'komodo dragon',
  'turtle',
  'tortoise',
  'frog',
  'toad',
  'salamander',
  'shark',
  'whale',
  'dolphin',
  'octopus',
  'squid',
  'jellyfish',
  'crab',
  'lobster',
  'scorpion',
  'spider',
  'beetle',
  'mantis',
  'butterfly',
  'moth',
  'dragonfly',
  'bee',
  'wasp',
  'dinosaur',
  't-rex',
  'raptor',
  'triceratops',
  'mammoth',
  'sabertooth',
  'cat',
  'dog',
  'wolfhound',
  'hound',
  'cow',
];

export const PROPS = [
  'sword',
  'longsword',
  'greatsword',
  'broadsword',
  'claymore',
  'katana',
  'scimitar',
  'rapier',
  'sabre',
  'cutlass',
  'dagger',
  'knife',
  'axe',
  'battle axe',
  'war hammer',
  'mace',
  'flail',
  'morning star',
  'spear',
  'halberd',
  'glaive',
  'lance',
  'trident',
  'scythe',
  'sickle',
  'bow',
  'longbow',
  'crossbow',
  'arrow',
  'quiver',
  'shield',
  'buckler',
  'tower shield',
  'staff',
  'wand',
  'orb',
  'scepter',
  'crown',
  'tiara',
  'helmet',
  'great helm',
  'plate armor',
  'chainmail',
  'leather armor',
  'gauntlet',
  'pauldron',
  'breastplate',
  'cloak',
  'cape',
  'hood',
  'robe',
  'tunic',
  'belt',
  'boots',
  'gloves',
  'mask',
  'amulet',
  'necklace',
  'ring',
  'jewel',
  'gem',
  'crystal',
  'potion',
  'potion bottle',
  'flask',
  'vial',
  'chalice',
  'goblet',
  'spellbook',
  'scroll',
  'map',
  'tome',
  'book',
  'candle',
  'lantern',
  'torch',
  'chest',
  'treasure chest',
  'coins',
  'key',
  'lock',
  'skull',
  'bones',
  'banner',
  'flag',
  'tent',
  'cart',
  'wagon',
  'saddle',
  'anvil',
  'cauldron',
  'throne',
  'altar',
  'statue',
  'totem',
  'idol',
  'relic',
  'artifact',
  'hourglass',
  'compass',
  'telescope',
  'clock',
  'musical instrument',
  'lute',
  'harp',
  'drum',
  'horn',
  'flute',
  'pipe',
  'tankard',
  'bread',
  'apple',
  'feast',
  'rope',
  'chain',
  'cage',
  'trap',
  'bomb',
  'cannon',
  'gun',
  'pistol',
  'musket',
  'rifle',
  'ship',
  'sailing ship',
  'airship',
  'boat',
  'carriage',
  'motorcycle',
  'car',
  'mech',
  'jewelry',
  'hat',
  'witch hat',
];

export const PLACES = [
  'castle',
  'fortress',
  'keep',
  'citadel',
  'tower',
  'wizard tower',
  'palace',
  'throne room',
  'great hall',
  'dungeon',
  'prison',
  'crypt',
  'tomb',
  'catacombs',
  'cathedral',
  'church',
  'temple',
  'shrine',
  'monastery',
  'ruins',
  'ruined temple',
  'ancient ruins',
  'city',
  'medieval city',
  'village',
  'town square',
  'market',
  'desert market',
  'harbor',
  'port',
  'docks',
  'bridge',
  'gate',
  'city gate',
  'wall',
  'street',
  'alley',
  'tavern',
  'tavern interior',
  'inn',
  'library',
  'laboratory',
  'alchemist lab',
  'forge',
  'smithy',
  'kitchen',
  'bedroom',
  'garden',
  'courtyard',
  'arena',
  'colosseum',
  'battlefield',
  'camp',
  'war camp',
  'forest',
  'misty forest',
  'dark forest',
  'enchanted forest',
  'forest path',
  'jungle',
  'swamp',
  'marsh',
  'bog',
  'meadow',
  'field',
  'farm',
  'hills',
  'mountains',
  'mountain pass',
  'snowy mountain pass',
  'cliff',
  'castle on a cliff',
  'canyon',
  'valley',
  'cave',
  'cavern',
  'crystal cave',
  'underground lake',
  'waterfall',
  'river',
  'lake',
  'ocean',
  'sea',
  'beach',
  'coast',
  'island',
  'desert',
  'dunes',
  'oasis',
  'tundra',
  'glacier',
  'volcano',
  'lava field',
  'wasteland',
  'graveyard',
  'cemetery',
  'battlefield at dusk',
  'sky',
  'clouds',
  'floating island',
  'sky city',
  'underwater city',
  'elven city',
  'dwarven hall',
  'mine',
  'portal',
  'stone circle',
  'lighthouse',
  'windmill',
  'cottage',
  'hut',
  'treehouse',
  'fantasy landscape',
  'landscape',
  'cityscape',
  'skyline',
  'interior',
  'exterior',
];

export const LOOK = [
  'rim light',
  'backlit',
  'backlit silhouette',
  'dramatic lighting',
  'soft light',
  'hard light',
  'god rays',
  'torchlight',
  'candlelight',
  'firelight',
  'moonlight',
  'sunlight',
  'golden hour',
  'sunset',
  'sunrise',
  'twilight',
  'dusk',
  'dawn',
  'night',
  'at night',
  'midday',
  'overcast',
  'fog',
  'mist',
  'in fog',
  'rain',
  'storm',
  'stormy sky',
  'snow',
  'blizzard',
  'lightning',
  'fire',
  'smoke',
  'embers',
  'sparks',
  'magic glow',
  'glowing',
  'bioluminescent',
  'neon',
  'high contrast',
  'low contrast',
  'chiaroscuro',
  'silhouette against the sky',
  'cold palette',
  'warm palette',
  'monochrome',
  'black and white',
  'sepia',
  'muted colors',
  'vibrant colors',
  'seen from below',
  'from below',
  'low angle',
  'seen from above',
  'from above',
  'high angle',
  "bird's eye view",
  "worm's eye view",
  'side view',
  'profile',
  'front view',
  'back view',
  'three-quarter view',
  'over the shoulder',
  'dutch angle',
  'wide shot',
  'establishing shot',
  'medium shot',
  'close up',
  'extreme close-up',
  'fisheye',
  'symmetrical',
  'centered composition',
  'rule of thirds',
  'depth of field',
  'bokeh',
  'motion lines',
  'moody',
  'epic',
  'serene',
  'eerie',
  'creepy',
  'horror',
  'dark fantasy',
  'grimdark',
  'whimsical',
  'cozy',
  'heroic',
  'melancholic',
  'mysterious',
  'romantic',
  'painterly',
  'oil painting',
  'watercolor',
  'ink drawing',
  'pencil sketch',
  'charcoal',
  'line art',
  'concept art',
  'splash art',
  'card art',
  'illustration',
  'digital painting',
  'photograph',
  'photo',
  'studio photo',
  '3d render',
  'anime',
  'manga',
  'comic',
  'pixel art',
  'low poly',
  'art nouveau',
  'baroque',
  'medieval manuscript',
  'woodcut',
  'engraving',
  'ukiyo-e',
  'stained glass',
  'tarot card',
  'sculpture',
  'marble statue',
];

// Styles, genres and everyday things people ask for that the lists above miss.
export const EXTRA = [
  'cyberpunk', 'steampunk', 'solarpunk', 'dieselpunk', 'biopunk', 'gothic', 'victorian', 'art deco', 'film noir', 'post-apocalyptic',
  'sci-fi', 'science fiction', 'space opera', 'western', 'wuxia', 'xianxia', 'shonen', 'chibi', 'kawaii', 'mecha', 'kaiju',
  'umbrella', 'chair', 'table', 'bench', 'ladder', 'bucket', 'basket', 'barrel', 'crate', 'bottle', 'mirror', 'door', 'window',
  'stairs', 'bed', 'desk', 'bookshelf', 'fireplace', 'carpet', 'curtain', 'vase', 'teapot', 'kimono', 'hanbok', 'sari', 'hoodie',
  'jacket', 'coat', 'dress', 'gown', 'uniform', 'armor set', 'punch', 'uppercut', 'foreshortened', 'foreshortening pose',
  'horseback', 'hobbit', 'hobbit house', 'gnome', 'kobold', 'tabaxi', 'aarakocra', 'genasi', 'warforged', 'drow', 'dark elf',
  'high elf', 'wood elf', 'half-orc', 'lizardfolk', 'kenku', 'goliath', 'firbolg', 'yuan-ti', 'githyanki', 'aasimar',
]

export const MATERIALS = [
  'steel',
  'iron',
  'rusted iron',
  'gold',
  'silver',
  'bronze',
  'copper',
  'brass',
  'wood',
  'oak',
  'bone',
  'ivory',
  'leather',
  'fur',
  'silk',
  'velvet',
  'linen',
  'wool',
  'lace',
  'stone',
  'marble',
  'obsidian',
  'jade',
  'crystal',
  'glass',
  'ice',
  'feathers',
  'scales',
  'chitin',
  'moss',
  'vines',
  'flowers',
  'roses',
  'blood',
  'water',
  'lava',
  'ash',
  'sand',
  'mud',
  'red',
  'crimson',
  'orange',
  'yellow',
  'green',
  'emerald',
  'teal',
  'blue',
  'navy',
  'purple',
  'violet',
  'pink',
  'white',
  'black',
  'grey',
  'brown',
  'ornate',
  'engraved',
  'worn',
  'battle-worn',
  'broken',
  'ancient',
  'rusty',
  'polished',
  'glowing runes',
];

// Pose and framing phrases → Safebooru tags. Booru tagging is precise on pose, so these carry pose searches.
export const BOORU = {
  'holding a sword': ['holding_sword'],
  sword: ['sword'],
  'swinging a sword': ['swinging', 'sword'],
  'holding a spear': ['holding_polearm'],
  'drawing a bow': ['drawing_bow'],
  'aiming a bow': ['aiming', 'bow_(weapon)'],
  'holding a staff': ['holding_staff'],
  'holding a dagger': ['holding_dagger'],
  'dual wielding': ['dual_wielding'],
  'holding a gun': ['holding_gun'],
  'casting a spell': ['magic'],
  'holding a shield': ['holding_shield'],
  'holding an axe': ['holding_axe'],
  'dynamic pose': ['dynamic_pose'],
  'action pose': ['dynamic_pose'],
  'fighting stance': ['fighting_stance'],
  'battle stance': ['fighting_stance'],
  running: ['running'],
  sprinting: ['running'],
  walking: ['walking'],
  jumping: ['jumping'],
  leaping: ['jumping'],
  falling: ['falling'],
  flying: ['flying'],
  floating: ['floating'],
  climbing: ['climbing'],
  crouching: ['squatting'],
  kneeling: ['kneeling'],
  sitting: ['sitting'],
  'lying down': ['lying'],
  sleeping: ['sleeping'],
  punching: ['punching'],
  kicking: ['kicking'],
  'high kick': ['high_kick'],
  'flying kick': ['flying_kick'],
  lunging: ['lunge'],
  'sword lunge': ['lunge', 'sword'],
  charging: ['running'],
  'arms raised': ['arms_up'],
  'arms up': ['arms_up'],
  'arms spread': ['outstretched_arms'],
  'arms crossed': ['crossed_arms'],
  'hands on hips': ['hands_on_hips'],
  'reaching out': ['reaching'],
  pointing: ['pointing'],
  'looking back': ['looking_back'],
  'looking up': ['looking_up'],
  'looking over shoulder': ['looking_back'],
  'from below': ['from_below'],
  'seen from below': ['from_below'],
  'low angle': ['from_below'],
  'from above': ['from_above'],
  'seen from above': ['from_above'],
  'side view': ['from_side'],
  profile: ['profile'],
  'back view': ['from_behind'],
  'full body': ['full_body'],
  'upper body': ['upper_body'],
  'close up': ['close-up'],
  silhouette: ['silhouette'],
  backlit: ['backlighting'],
  'rim light': ['backlighting'],
  'riding a horse': ['horseback_riding'],
  'riding a dragon': ['riding', 'dragon'],
  dragon: ['dragon'],
  knight: ['knight'],
  armor: ['armor'],
  'plate armor': ['armor'],
  cape: ['cape'],
  cloak: ['cloak'],
  'cape flowing': ['cape', 'wind'],
  'mid-air': ['midair'],
  'mid-swing': ['swinging'],
  'motion blur': ['motion_blur'],
  'motion lines': ['motion_lines'],
  'two-handed': ['two-handed'],
  foreshortening: ['foreshortening'],
  twisting: ['twisted_torso'],
  wolf: ['wolf'],
  man: ['1boy'],
  woman: ['1girl'],
  boy: ['1boy'],
  girl: ['1girl'],
  samurai: ['samurai'],
  ninja: ['ninja'],
  witch: ['witch'],
  wizard: ['wizard'],
  elf: ['elf'],
  katana: ['katana'],
  spear: ['spear'],
  bow: ['bow_(weapon)'],
};

// Nouns Scryfall's art tagger knows (art:<tag>). Used to phrase MTG queries.
export const SCRYFALL_ART = [
  'sword',
  'axe',
  'spear',
  'bow',
  'shield',
  'staff',
  'dagger',
  'hammer',
  'armor',
  'helmet',
  'crown',
  'knight',
  'warrior',
  'soldier',
  'samurai',
  'ninja',
  'wizard',
  'witch',
  'angel',
  'demon',
  'vampire',
  'zombie',
  'skeleton',
  'ghost',
  'elf',
  'dwarf',
  'goblin',
  'orc',
  'giant',
  'dragon',
  'wolf',
  'bear',
  'cat',
  'dog',
  'horse',
  'bird',
  'owl',
  'raven',
  'snake',
  'spider',
  'fish',
  'octopus',
  'castle',
  'tower',
  'city',
  'ruins',
  'forest',
  'mountain',
  'cave',
  'ocean',
  'island',
  'desert',
  'swamp',
  'river',
  'waterfall',
  'volcano',
  'fire',
  'lightning',
  'moon',
  'sun',
  'storm',
  'skull',
  'book',
  'potion',
  'ship',
  'throne',
  'portal',
  'battle',
  'duel',
  'running',
  'flying',
  'kneeling',
  'jumping',
  'riding',
  'casting',
  'praying',
  'dancing',
];
